### ISSUE TITLE
Processing files unaltering the content

### ISSUE THREAD

**Issue by cesarjorgemartinez** [skyzyx/yml2json#3]
Hi,
I see your yml2json and is a great tool. Testing with a example yaml file to convert to json, I see that this tool generate the json in other ordered lists, in the first level and next levels.

Example input:

```yaml
ss-a:
  oneitem: oneitem1
  item: value1
  vol:
    - myvol
  text:
    - mytext
  mylist:
    type: theitem1
    flavor: theitem2

ss-b:
  otheritem: text1

ss-c:
  oneitem: oneitem1
  item: value1

ss-d:
  oneitem: oneitem1
  item: value1

ss-e:
  oneitem: oneitem1
  item: value1

ss-f:
  oneitem: oneitem1
  item: value1

ss-g:
  oneitem: oneitem1
  item: value1

ss-h:
  oneitem: oneitem1
  item: value1

ss-i:
  oneitem: oneitem1
  item: value1

ss-j:
  oneitem: oneitem1
  item: value1
```

Exist a fix or option for this behavior?

Regards

----
Edit by @skyzyx: Grammar and formatting.
